site_name: Gitalong Protocol Spec
site_description: Building a better chat protocol
site_author: Gitalong
repo_url: https://github.com/ivanmirakov/gitalong-spec

theme:
  name: readthedocs
  features:
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - content.code.copy
  font:
    text: Ubuntu

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true # Adds those clickable icons to headers
  - admonition # For "Note" and "Warning" boxes I will definitely use
